// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: rcode.proto

package rcode

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RcodeClient is the client API for Rcode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RcodeClient interface {
	LaunchCode(ctx context.Context, in *LaunchRequest, opts ...grpc.CallOption) (*LaunchResponse, error)
}

type rcodeClient struct {
	cc grpc.ClientConnInterface
}

func NewRcodeClient(cc grpc.ClientConnInterface) RcodeClient {
	return &rcodeClient{cc}
}

func (c *rcodeClient) LaunchCode(ctx context.Context, in *LaunchRequest, opts ...grpc.CallOption) (*LaunchResponse, error) {
	out := new(LaunchResponse)
	err := c.cc.Invoke(ctx, "/Rcode/LaunchCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RcodeServer is the server API for Rcode service.
// All implementations must embed UnimplementedRcodeServer
// for forward compatibility
type RcodeServer interface {
	LaunchCode(context.Context, *LaunchRequest) (*LaunchResponse, error)
	mustEmbedUnimplementedRcodeServer()
}

// UnimplementedRcodeServer must be embedded to have forward compatible implementations.
type UnimplementedRcodeServer struct {
}

func (UnimplementedRcodeServer) LaunchCode(context.Context, *LaunchRequest) (*LaunchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LaunchCode not implemented")
}
func (UnimplementedRcodeServer) mustEmbedUnimplementedRcodeServer() {}

// UnsafeRcodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RcodeServer will
// result in compilation errors.
type UnsafeRcodeServer interface {
	mustEmbedUnimplementedRcodeServer()
}

func RegisterRcodeServer(s grpc.ServiceRegistrar, srv RcodeServer) {
	s.RegisterService(&Rcode_ServiceDesc, srv)
}

func _Rcode_LaunchCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RcodeServer).LaunchCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Rcode/LaunchCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RcodeServer).LaunchCode(ctx, req.(*LaunchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rcode_ServiceDesc is the grpc.ServiceDesc for Rcode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rcode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Rcode",
	HandlerType: (*RcodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LaunchCode",
			Handler:    _Rcode_LaunchCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rcode.proto",
}
